# Generated by Django 4.2.6 on 2023-11-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('venue', models.CharField(max_length=250, verbose_name='Venue')),
                ('event_type', models.CharField(max_length=250, verbose_name='EventType')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_date',models.DateField(verbose_name='Date')),
                ('event_time',models.TimeField(verbose_name='Time',default='12:00:00')),
            ],
        ),
    ]
