# Generated by Django 4.2.6 on 2023-11-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_date', models.DateField(verbose_name='Date')),
                ('event_duration_value', models.PositiveIntegerField(verbose_name='Duration Value')),
                ('event_duration_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=11, verbose_name='Duration Unit')),
                ('venue', models.CharField(max_length=250, verbose_name='Venue')),
                ('organizer', models.CharField(max_length=250, verbose_name='Organizer')),
                ('banner', models.FileField(blank=True, null=True, upload_to='events_banner/')),
                ('tickets', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Tickets')),
            ],
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.IntegerField(default='0001', editable=False, unique=True, verbose_name='Ticket No')),
                ('ticket_type', models.CharField(choices=[('vvip', 'VVIP'), ('vip', 'VIP'), ('regular', 'Regular')], max_length=50, verbose_name='Ticket Type')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('bank', 'Bank'), ('credit', 'Credit'), ('visa', 'Visa')], max_length=50, verbose_name='Payment Method')),
                ('amount', models.PositiveBigIntegerField(editable=False, verbose_name='Amount')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='events.event')),
            ],
        ),
    ]
