# Generated by Django 4.2.6 on 2023-11-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdms_app', '0002_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
